# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty

# Setup
title:            Stephen Mayhew
tagline:          'Homepage'
description:      'Homepage'
url:              http://mayhewsw.github.io
baseurl:

author:
  name:           'Stephen Mayhew'
  url:            https://twitter.com/mayhewsw


# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mayhewsw

plugins: [jekyll-paginate]
paginate: 5
paginate_path: "/blog/page:num/"
disqusShortname : spf13
