# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty

# Setup
title:            Stephen Mayhew
tagline:          'My Academic Blog'
description:      'Academic Blog'
url:              http://cogcomp.cs.illinois.edu/~mayhew2
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mayhewsw



# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mayhewsw

gems: [jekyll-paginate]       
paginate: 5
paginate_path: "page:num"
